version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    expose: 
          - 80
          - 443
    networks:
          - nginx-test-net

    
  nginx-cluster-1:
    image: nginx:latest
    ports:
        - "8080:80"
        - "643:443"
    links:
        - nginx
    volumes:
        - ./nginx-cluster-1/conf.d/:/etc/nginx/conf.d/:ro
        - ./nginx-cluster-1/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx-cluster-1/log/:/var/log/nginx-cluster-1/:rw
    networks:
          - nginx-test-net


networks:
  nginx-test-net:
    ipam:
      config:
        - subnet: 172.30.0.0/16